In [1]:
import numpy as np

np.random.rand()


0.7711827181457042

In [2]:
np.random.rand(4)

array([0.46063885, 0.87655828, 0.48027011, 0.0259348 ])

In [4]:
np.random.rand(4,2)

array([[0.73689562, 0.65792649],
       [0.88205072, 0.96064715],
       [0.49515698, 0.79685095],
       [0.66543751, 0.70997934]])

In [6]:
from random import uniform


np.random,uniform(10, size=[2,2,2])

TypeError: Random.uniform() got an unexpected keyword argument 'size'

In [7]:
np.random.randint(10)

2

In [8]:
np.random.randint(10, size=[3,2])

array([[3, 0],
       [1, 5],
       [4, 4]])